export type Country = {
  code: string;
  name: string;
  flag: string;
  dialCode: string;
};

// 100+ countries (major + popular destinations)
export const COUNTRIES: Country[] = [
  { code: "AF", name: "Afghanistan", flag: "🇦🇫", dialCode: "93" },
  { code: "AL", name: "Albania", flag: "🇦🇱", dialCode: "355" },
  { code: "DZ", name: "Algeria", flag: "🇩🇿", dialCode: "213" },
  { code: "AR", name: "Argentina", flag: "🇦🇷", dialCode: "54" },
  { code: "AM", name: "Armenia", flag: "🇦🇲", dialCode: "374" },
  { code: "AU", name: "Australia", flag: "🇦🇺", dialCode: "61" },
  { code: "AT", name: "Austria", flag: "🇦🇹", dialCode: "43" },
  { code: "AZ", name: "Azerbaijan", flag: "🇦🇿", dialCode: "994" },
  { code: "BH", name: "Bahrain", flag: "🇧🇭", dialCode: "973" },
  { code: "BD", name: "Bangladesh", flag: "🇧🇩", dialCode: "880" },
  { code: "BY", name: "Belarus", flag: "🇧🇾", dialCode: "375" },
  { code: "BE", name: "Belgium", flag: "🇧🇪", dialCode: "32" },
  { code: "BO", name: "Bolivia", flag: "🇧🇴", dialCode: "591" },
  { code: "BA", name: "Bosnia & Herzegovina", flag: "🇧🇦", dialCode: "387" },
  { code: "BR", name: "Brazil", flag: "🇧🇷", dialCode: "55" },
  { code: "BG", name: "Bulgaria", flag: "🇧🇬", dialCode: "359" },
  { code: "KH", name: "Cambodia", flag: "🇰🇭", dialCode: "855" },
  { code: "CM", name: "Cameroon", flag: "🇨🇲", dialCode: "237" },
  { code: "CA", name: "Canada", flag: "🇨🇦", dialCode: "1" },
  { code: "CL", name: "Chile", flag: "🇨🇱", dialCode: "56" },
  { code: "CN", name: "China", flag: "🇨🇳", dialCode: "86" },
  { code: "CO", name: "Colombia", flag: "🇨🇴", dialCode: "57" },
  { code: "CR", name: "Costa Rica", flag: "🇨🇷", dialCode: "506" },
  { code: "HR", name: "Croatia", flag: "🇭🇷", dialCode: "385" },
  { code: "CY", name: "Cyprus", flag: "🇨🇾", dialCode: "357" },
  { code: "CZ", name: "Czechia", flag: "🇨🇿", dialCode: "420" },
  { code: "DK", name: "Denmark", flag: "🇩🇰", dialCode: "45" },
  { code: "DO", name: "Dominican Republic", flag: "🇩🇴", dialCode: "1" },
  { code: "EC", name: "Ecuador", flag: "🇪🇨", dialCode: "593" },
  { code: "EG", name: "Egypt", flag: "🇪🇬", dialCode: "20" },
  { code: "SV", name: "El Salvador", flag: "🇸🇻", dialCode: "503" },
  { code: "EE", name: "Estonia", flag: "🇪🇪", dialCode: "372" },
  { code: "ET", name: "Ethiopia", flag: "🇪🇹", dialCode: "251" },
  { code: "FI", name: "Finland", flag: "🇫🇮", dialCode: "358" },
  { code: "FR", name: "France", flag: "🇫🇷", dialCode: "33" },
  { code: "GE", name: "Georgia", flag: "🇬🇪", dialCode: "995" },
  { code: "DE", name: "Germany", flag: "🇩🇪", dialCode: "49" },
  { code: "GH", name: "Ghana", flag: "🇬🇭", dialCode: "233" },
  { code: "GR", name: "Greece", flag: "🇬🇷", dialCode: "30" },
  { code: "GT", name: "Guatemala", flag: "🇬🇹", dialCode: "502" },
  { code: "HN", name: "Honduras", flag: "🇭🇳", dialCode: "504" },
  { code: "HK", name: "Hong Kong", flag: "🇭🇰", dialCode: "852" },
  { code: "HU", name: "Hungary", flag: "🇭🇺", dialCode: "36" },
  { code: "IS", name: "Iceland", flag: "🇮🇸", dialCode: "354" },
  { code: "IN", name: "India", flag: "🇮🇳", dialCode: "91" },
  { code: "ID", name: "Indonesia", flag: "🇮🇩", dialCode: "62" },
  { code: "IQ", name: "Iraq", flag: "🇮🇶", dialCode: "964" },
  { code: "IE", name: "Ireland", flag: "🇮🇪", dialCode: "353" },
  { code: "IL", name: "Israel", flag: "🇮🇱", dialCode: "972" },
  { code: "IT", name: "Italy", flag: "🇮🇹", dialCode: "39" },
  { code: "JM", name: "Jamaica", flag: "🇯🇲", dialCode: "1" },
  { code: "JP", name: "Japan", flag: "🇯🇵", dialCode: "81" },
  { code: "JO", name: "Jordan", flag: "🇯🇴", dialCode: "962" },
  { code: "KZ", name: "Kazakhstan", flag: "🇰🇿", dialCode: "7" },
  { code: "KE", name: "Kenya", flag: "🇰🇪", dialCode: "254" },
  { code: "KW", name: "Kuwait", flag: "🇰🇼", dialCode: "965" },
  { code: "LV", name: "Latvia", flag: "🇱🇻", dialCode: "371" },
  { code: "LB", name: "Lebanon", flag: "🇱🇧", dialCode: "961" },
  { code: "LY", name: "Libya", flag: "🇱🇾", dialCode: "218" },
  { code: "LT", name: "Lithuania", flag: "🇱🇹", dialCode: "370" },
  { code: "LU", name: "Luxembourg", flag: "🇱🇺", dialCode: "352" },
  { code: "MY", name: "Malaysia", flag: "🇲🇾", dialCode: "60" },
  { code: "MV", name: "Maldives", flag: "🇲🇻", dialCode: "960" },
  { code: "MT", name: "Malta", flag: "🇲🇹", dialCode: "356" },
  { code: "MX", name: "Mexico", flag: "🇲🇽", dialCode: "52" },
  { code: "MN", name: "Mongolia", flag: "🇲🇳", dialCode: "976" },
  { code: "MA", name: "Morocco", flag: "🇲🇦", dialCode: "212" },
  { code: "NP", name: "Nepal", flag: "🇳🇵", dialCode: "977" },
  { code: "NL", name: "Netherlands", flag: "🇳🇱", dialCode: "31" },
  { code: "NZ", name: "New Zealand", flag: "🇳🇿", dialCode: "64" },
  { code: "NG", name: "Nigeria", flag: "🇳🇬", dialCode: "234" },
  { code: "NO", name: "Norway", flag: "🇳🇴", dialCode: "47" },
  { code: "OM", name: "Oman", flag: "🇴🇲", dialCode: "968" },
  { code: "PK", name: "Pakistan", flag: "🇵🇰", dialCode: "92" },
  { code: "PA", name: "Panama", flag: "🇵🇦", dialCode: "507" },
  { code: "PE", name: "Peru", flag: "🇵🇪", dialCode: "51" },
  { code: "PH", name: "Philippines", flag: "🇵🇭", dialCode: "63" },
  { code: "PL", name: "Poland", flag: "🇵🇱", dialCode: "48" },
  { code: "PT", name: "Portugal", flag: "🇵🇹", dialCode: "351" },
  { code: "QA", name: "Qatar", flag: "🇶🇦", dialCode: "974" },
  { code: "RO", name: "Romania", flag: "🇷🇴", dialCode: "40" },
  { code: "RU", name: "Russia", flag: "🇷🇺", dialCode: "7" },
  { code: "SA", name: "Saudi Arabia", flag: "🇸🇦", dialCode: "966" },
  { code: "RS", name: "Serbia", flag: "🇷🇸", dialCode: "381" },
  { code: "SG", name: "Singapore", flag: "🇸🇬", dialCode: "65" },
  { code: "SK", name: "Slovakia", flag: "🇸🇰", dialCode: "421" },
  { code: "SI", name: "Slovenia", flag: "🇸🇮", dialCode: "386" },
  { code: "ZA", name: "South Africa", flag: "🇿🇦", dialCode: "27" },
  { code: "KR", name: "South Korea", flag: "🇰🇷", dialCode: "82" },
  { code: "ES", name: "Spain", flag: "🇪🇸", dialCode: "34" },
  { code: "LK", name: "Sri Lanka", flag: "🇱🇰", dialCode: "94" },
  { code: "SE", name: "Sweden", flag: "🇸🇪", dialCode: "46" },
  { code: "CH", name: "Switzerland", flag: "🇨🇭", dialCode: "41" },
  { code: "TW", name: "Taiwan", flag: "🇹🇼", dialCode: "886" },
  { code: "TH", name: "Thailand", flag: "🇹🇭", dialCode: "66" },
  { code: "TN", name: "Tunisia", flag: "🇹🇳", dialCode: "216" },
  { code: "TR", name: "Turkey", flag: "🇹🇷", dialCode: "90" },
  { code: "UA", name: "Ukraine", flag: "🇺🇦", dialCode: "380" },
  { code: "AE", name: "United Arab Emirates", flag: "🇦🇪", dialCode: "971" },
  { code: "GB", name: "United Kingdom", flag: "🇬🇧", dialCode: "44" },
  { code: "US", name: "United States", flag: "🇺🇸", dialCode: "1" },
  { code: "UY", name: "Uruguay", flag: "🇺🇾", dialCode: "598" },
  { code: "UZ", name: "Uzbekistan", flag: "🇺🇿", dialCode: "998" },
  { code: "VE", name: "Venezuela", flag: "🇻🇪", dialCode: "58" },
  { code: "VN", name: "Vietnam", flag: "🇻🇳", dialCode: "84" },
  { code: "YE", name: "Yemen", flag: "🇾🇪", dialCode: "967" },
];

export function findCountryByCode(code?: string | null): Country | undefined {
  if (!code) return undefined;
  return COUNTRIES.find((c) => c.code === code);
}

